name: Lint nix

on:
  workflow_call:

permissions: {}

jobs:
  nixpkgs-fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: actions/checkout@v4.2.0
      - name: Check formatting
        run: |
          nix run --inputs-from . nixpkgs#nixpkgs-fmt -- --check .

  statix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: actions/checkout@v4.2.0
      - name: Static code analysis
        run: |
          nix run --inputs-from . nixpkgs#statix -- check .

  deadnix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: actions/checkout@v4.2.0
      - name: Check for dead code
        run: |
          nix run --inputs-from . nixpkgs#deadnix -- -f