name: Lint package

on:
  workflow_call:
    inputs:
      emacs-versions:
        required: true
        type: string

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        emacs_version: ${{ fromJson(inputs.emacs-versions) }}

    steps:
      - uses: actions/checkout@v3.6.0
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: conao3/setup-cask@master
        with:
          version: snapshot
      - run: make lint

  collect-lint:
    needs: [lint]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all matrix job status
        if: >-
          ${{
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1