name: "Validate PR title"

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}


jobs:
  validate:
    permissions:
      contents: read
      pull-requests: read
    name: Lint title
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@0cf5902181e78341bb97bb06646396e5bd354b3f # v1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/pr-title-checker-config.json"