name: Test package

on:
  workflow_call:
    inputs:
      emacs-versions:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version: ${{ fromJson(inputs.emacs-versions) }}

    steps:
      - uses: actions/checkout@v4.1.5
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: conao3/setup-cask@master
        with:
          version: snapshot
      - name: Install Nix grammar
        run: |
          emacs -batch -l test/scripts/install-nix-grammar.el
      - name: Run ERT units
        run: make test
      - name: Cleanup
        run: make clean

  collect-tests:
    needs: [test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all matrix job status
        if: >-
          ${{
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
        run: exit 1
